      COMMON/eqf/phl_mult,rmyc_mult,DCKI_MULT,TSORP_MULT,SPOHA_MULT
     2,SPOHC_MULT,OQKM_MULT,VMXO_MULT,DCKM_MULT,DCKM0_MULT,DCKML_MULT
     3,ETMX_MULT,VCMX_MULT,VCMX4_MULT,QNTM_MULT,VOMX_MULT,XKCO2_MULT
     4,XKO2_MULT,osm_mult
